/* ═══════════════════════════════════════════════════════════════════════════════════
   HÉROE VITAL — lang.js
   EN / ES translation system
   ═══════════════════════════════════════════════════════════════════════════════════ */

'use strict';

window.LANG_CODE = 'en'; // Force English

const TRANSLATIONS = {

/* ════════════════════════════════ ESPAÑOL ════════════════════════════════════════ */
es: {
  /* App name */
  'app.name': 'HÉROE VITAL',
  'app.tagline': 'Tu aventura de salud',

  /* Language screen */
  'lang.choose': 'ELIGE TU IDIOMA',

  /* Auth */
  'auth.login':           'INICIAR SESIÓN',
  'auth.register':        'CREAR CUENTA',
  'auth.username':        'NOMBRE DE USUARIO',
  'auth.password':        'CONTRASEÑA',
  'auth.confirm':         'CONFIRMAR CONTRASEÑA',
  'auth.btn.login':       'ENTRAR',
  'auth.btn.register':    'REGISTRARSE',
  'auth.switch.register': '¿Sin cuenta? Regístrate aquí',
  'auth.switch.login':    '¿Ya tienes cuenta? Inicia sesión',
  'auth.offline':         'JUGAR SIN CUENTA',
  'auth.your_id':         'TU ID ONLINE:',
  'auth.err.nouser':      '¡Usuario no encontrado!',
  'auth.err.wrongpass':   '¡Contraseña incorrecta!',
  'auth.err.taken':       '¡Ese nombre de usuario ya existe!',
  'auth.err.passmatch':   '¡Las contraseñas no coinciden!',
  'auth.err.shortpass':   'La contraseña debe tener al menos 4 caracteres',
  'auth.err.shortuser':   'El usuario debe tener al menos 3 caracteres',
  'auth.err.fill':        '¡Completa todos los campos!',
  'auth.welcome':         '¡Bienvenido,',
  'auth.logged_out':      '¡Sesión cerrada!',

  /* Onboarding */
  'ob.subtitle':     'Tu aventura de salud comienza aquí',
  'ob.player_name':  'NOMBRE DE JUGADOR',
  'ob.hero_name':    'NOMBRE DEL HÉROE',
  'ob.btn.start':    'COMENZAR →',
  'ob.physical':     '📊 DATOS FÍSICOS',
  'ob.weight':       'PESO (kg)',
  'ob.height':       'ALTURA (cm)',
  'ob.age':          'EDAD',
  'ob.sex':          'SEXO',
  'ob.sex.m':        'Masculino',
  'ob.sex.f':        'Femenino',
  'ob.sex.o':        'Otro',
  'ob.goal.title':   '🎯 ¿CUÁL ES TU OBJETIVO?',
  'ob.goal.lose':    'PERDER PESO',
  'ob.goal.lose.d':  'Déficit calórico y cardio',
  'ob.goal.define':  'DEFINIRSE',
  'ob.goal.define.d':'Tonificar y reducir grasa',
  'ob.goal.maintain':'MANTENERSE',
  'ob.goal.maintain.d':'Mantener composición actual',
  'ob.goal.mass':    'GANAR MASA',
  'ob.goal.mass.d':  'Superávit + alta proteína',
  'ob.goal.strength':'GANAR FUERZA',
  'ob.goal.strength.d':'Fuerza máxima y potencia',
  'ob.activity.title':'🏃 NIVEL DE ACTIVIDAD',
  'ob.act.sedentary': 'SEDENTARIO',
  'ob.act.sedentary.d':'Poco o nada de ejercicio',
  'ob.act.light':    'LIGERAMENTE ACTIVO',
  'ob.act.light.d':  'Ejercicio 1-3 días/semana',
  'ob.act.moderate': 'MODERADAMENTE ACTIVO',
  'ob.act.moderate.d':'Ejercicio 3-5 días/semana',
  'ob.act.high':     'MUY ACTIVO',
  'ob.act.high.d':   'Entreno intenso 6-7 días',
  'ob.act.athlete':  'ATLÉTICO',
  'ob.act.athlete.d':'Deportista o trabajo físico',
  'ob.class.title':  '🧙 ELIGE TU CLASE',
  'ob.class.warrior.d':'Maestro del combate cuerpo a cuerpo',
  'ob.class.mage.d': 'Magia devastadora con bonus proteína',
  'ob.class.archer.d':'Ágil y veloz, potenciado por actividad',
  'ob.class.healer.d':'Resistencia suprema, recupera PS rápido',
  'ob.summary':      '✅ ¡RESUMEN!',
  'ob.btn.back':     '← ATRÁS',
  'ob.btn.next':     'SIGUIENTE →',
  'ob.btn.play':     '⚔️ ¡COMENZAR AVENTURA!',
  'ob.err.names':    '¡Ingresa tu nombre y el nombre del héroe!',
  'ob.err.data':     '¡Completa todos los datos físicos!',
  'ob.err.goal':     '¡Elige tu objetivo!',
  'ob.err.activity': '¡Elige tu nivel de actividad!',
  'ob.err.class':    '¡Elige tu clase de personaje!',

  /* HUD */
  'hud.lv':      'NV',
  'hud.streak':  'RACHA:',
  'hud.cal':     'cal',
  'hud.ml':      'ml',
  'hud.alert.hunger': '¡HAMBRE!',
  'hud.alert.thirst': '¡SED!',
  'hud.alert.weak':   '¡DEBILITADO!',

  /* Tabs */
  'tab.home':    '🏠 INICIO',
  'tab.log':     '📸 REGISTRO',
  'tab.friends': '👥 AMIGOS',
  'tab.shop':    '🛒 TIENDA',
  'tab.free':    '⚡ BATALLA LIBRE',

  /* Home */
  'home.castle':   '🏠 MI CASTILLO',
  'home.stats':    '⚔️ ESTADÍSTICAS DEL HÉROE',
  'home.goals':    '🎯 METAS DE HOY',
  'home.history':  '🏆 HISTORIAL DE BATALLAS',
  'home.no_battles':'Sin batallas aún.',
  'home.speech.hungry': '¡Tengo mucha hambre! 🍗',
  'home.speech.thirsty':'¡Necesito agua! 💧',
  'home.speech.weak':   '¡Estoy debilitado...',
  'home.speech.strong': '¡Soy muy poderoso! ⚡',
  'home.speech.ok':     '¡Cuídame bien!',

  /* Stats */
  'stat.attack':  '⚔️ ATAQUE',
  'stat.defense': '🛡️ DEFENSA',
  'stat.agility': '⚡ AGILIDAD',
  'stat.strength':'💪 FUERZA',
  'stat.hp':      '❤️ PS',
  'stat.power':   '⚡ PODER',
  'stat.cal':     '🍽️ Calorías',
  'stat.protein': '🥩 Proteína',
  'stat.water':   '💧 Agua',

  /* Log */
  'log.title':    '📸 REGISTRAR ALIMENTO O BEBIDA',
  'log.photo':    'TOCA PARA FOTOGRAFIAR',
  'log.type':     'TIPO',
  'log.desc':     'DESCRIPCIÓN',
  'log.desc.ph':  '¿Qué comiste?',
  'log.cal':      'CALORÍAS',
  'log.prot':     'PROTEÍNAS(g)',
  'log.carbs':    'CARBS(g)',
  'log.water':    'AGUA(ml)',
  'log.btn':      '⚔️ REGISTRAR Y GANAR EXPERIENCIA',
  'log.today':    '📋 REGISTRO DE HOY',
  'log.empty':    'No hay registros hoy. ¡Empieza a comer!',
  'log.type.food':'🍽️ Comida',
  'log.type.water':'💧 Agua',
  'log.type.drink':'🥤 Bebida',
  'log.type.snack':'🍎 Snack',
  'log.type.supp': '💊 Suplemento',
  'log.err.desc': '¡Describe qué comiste o bebiste!',

  /* Friends */
  'friends.my_id':    '🆔 TU ID ONLINE',
  'friends.copy_id':  '📋 COPIAR ID',
  'friends.add':      '➕ AGREGAR AMIGO',
  'friends.add.name': 'Nombre de usuario del amigo...',
  'friends.add.btn':  'AGREGAR AMIGO',
  'friends.my_stats': '📊 MIS STATS DE BATALLA',
  'friends.list':     '👥 AMIGOS',
  'friends.empty':    'Sin amigos aún.\n¡Comparte tu ID para jugar!',
  'friends.battle':   '⚔️ BATALLAR',
  'friends.wins':     'victorias',
  'friends.losses':   'derrotas',
  'friends.streak':   'días de racha',
  'friends.coins':    'monedas',
  'friends.added':    '¡agregado como amigo!',
  'friends.err.name': '¡Ingresa el nombre del amigo!',
  'friends.logout':   'CERRAR SESIÓN',

  /* Shop */
  'shop.title':   '🛒 TIENDA DEL REINO',
  'shop.owned':   '✅ COMPRADO',
  'shop.none':    'Nada aún',
  'shop.cat.all': 'TODOS',
  'shop.cat.acc': '💍 ACCESORIOS',
  'shop.cat.arm': '⚔️ ARMAS',
  'shop.cat.armor':'🛡️ ARMADURAS',
  'shop.cat.furn':'🪑 MUEBLES',
  'shop.cat.deco':'🖼️ DECORACIONES',
  'shop.bought':  '¡comprado!',
  'shop.no_coins':'¡No tienes suficientes monedas!',

  /* Free Battle */
  'free.title':    '⚡ BATALLA LIBRE',
  'free.desc':     '¡Combate sin apuestas de monedas!\nSolo por gloria y diversión.',
  'free.online':   '🌐 DESAFÍO ONLINE',
  'free.peer_ph':  'Pega el ID de tu rival...',
  'free.challenge':'⚡ DESAFIAR ONLINE',
  'free.cpu':      '🤖 RIVALES DE PRÁCTICA (CPU)',
  'free.fight':    '⚔️ LUCHAR',
  'free.online.c': 'Conectado online ✓',
  'free.online.cn':'Conectando...',
  'free.online.dc':'Sin conexión',
  'free.sent':     '¡Desafío enviado! Esperando respuesta...',
  'free.err.id':   '¡Ingresa el ID de tu rival!',
  'free.incoming': '¡{name} te desafía a batalla! {type}',
  'free.libre_type':'(BATALLA LIBRE)',
  'free.coins_type':'(CON MONEDAS)',
  'free.accept':   '✅ ACEPTAR',
  'free.reject':   '❌ RECHAZAR',
  'free.rejected': 'El rival rechazó tu desafío.',
  'free.accepted': '¡Rival aceptó! Comenzando batalla...',
  'free.not_found':'Rival no encontrado. Verifica el ID.',
  'free.err_conn': 'Error de conexión online.',

  /* Battle */
  'battle.start':  '¡{name} quiere combatir!',
  'battle.begin':  '¡Comienza la batalla!',
  'battle.attack': '⚔️ ATACAR',
  'battle.special':'✨ ESPECIAL',
  'battle.defend': '🛡️ DEFENDER',
  'battle.flee':   '🏃 HUIR',
  'battle.escaped':'{name} huye de la batalla... 😨',
  'battle.no_flee':'¡No puedes escapar! 😱',
  'battle.p_dmg':  '{name} usa {move}! -{dmg} PS al enemigo.',
  'battle.p_crit': '¡{name} usa {move}! ¡GOLPE CRÍTICO! -{dmg} PS ⚡',
  'battle.e_dmg':  '{enemy} usa {move}! -{dmg} PS a {name}.',
  'battle.e_crit': '¡{enemy} usa {move}! ¡CRÍTICO! -{dmg} PS ⚡',
  'battle.victory':'¡{name} GANÓ LA BATALLA! 🏆',
  'battle.defeat': '{name} fue derrotado... 💀',
  'battle.draw':   '¡La batalla terminó en empate! 🤝',
  'battle.result.v':'¡VICTORIA!',
  'battle.result.d':'DERROTA',
  'battle.result.e':'EMPATE',
  'battle.libre_note':'⚡ BATALLA LIBRE - Sin apuestas',
  'battle.coins_won': '+{n} 🪙 monedas robadas',
  'battle.coins_lost':'-{n} 🪙 monedas perdidas',
  'battle.exp_gain':  '+{n} EXP',
  'battle.vs':        'vs',

  /* Level up */
  'lvlup.title':  '¡SUBISTE DE NIVEL!',
  'lvlup.nivel':  'NIVEL',
  'lvlup.gains':  '⚔️ ATQ +2 | 🛡️ DEF +2\n⚡ AGI +1 | 💪 FUE +2\n❤️ PS MAX +15 | 🪙 +30',

  /* Battle history */
  'bh.victory': '🏆 VICTORIA',
  'bh.defeat':  '💀 DERROTA',
  'bh.draw':    '🤝 EMPATE',

  /* Misc */
  'modal.close': 'CERRAR',
  'copied':      '¡ID copiado al portapapeles!',
  'daily_bonus': '🎉 ¡{n}/3 metas cumplidas! +{coins} 🪙 | Racha: {streak} días',
  'ps_label':    'PS',

  /* Summary */
  'sum.player':  '👤 Jugador:',
  'sum.hero':    'Héroe:',
  'sum.weight':  'Peso:',
  'sum.height':  'Altura:',
  'sum.age':     'Edad:',
  'sum.goal':    '🎯 Objetivo:',
  'sum.activity':'🏃 Actividad:',
  'sum.cal_meta':'🔥 Meta calórica:',
  'sum.prot_meta':'🥩 Meta proteína:',
  'sum.water_meta':'💧 Meta agua:',
  'sum.stats':   '⚔️ Stats iniciales:',
  'sum.kg':      'kg',
  'sum.cm':      'cm',
  'sum.kcal_day':'kcal/día',
  'sum.g_day':   'g/día',
  'sum.ml_day':  'ml/día',
},

/* ════════════════════════════════ ENGLISH ════════════════════════════════════════ */
en: {
  /* App name */
  'app.name': 'VITAL HERO',
  'app.tagline': 'Your health adventure',

  /* Language screen */
  'lang.choose': 'CHOOSE YOUR LANGUAGE',

  /* Auth */
  'auth.login':           'LOGIN',
  'auth.register':        'CREATE ACCOUNT',
  'auth.username':        'USERNAME',
  'auth.password':        'PASSWORD',
  'auth.confirm':         'CONFIRM PASSWORD',
  'auth.btn.login':       'ENTER',
  'auth.btn.register':    'REGISTER',
  'auth.switch.register': 'No account? Sign up here',
  'auth.switch.login':    'Have an account? Log in',
  'auth.offline':         'PLAY WITHOUT ACCOUNT',
  'auth.your_id':         'YOUR ONLINE ID:',
  'auth.err.nouser':      'User not found!',
  'auth.err.wrongpass':   'Wrong password!',
  'auth.err.taken':       'Username already taken!',
  'auth.err.passmatch':   'Passwords do not match!',
  'auth.err.shortpass':   'Password must be at least 4 characters',
  'auth.err.shortuser':   'Username must be at least 3 characters',
  'auth.err.fill':        'Please fill in all fields!',
  'auth.welcome':         'Welcome,',
  'auth.logged_out':      'Logged out!',

  /* Onboarding */
  'ob.subtitle':    'Your health adventure starts here',
  'ob.player_name': 'PLAYER NAME',
  'ob.hero_name':   'HERO NAME',
  'ob.btn.start':   'BEGIN →',
  'ob.physical':    '📊 PHYSICAL DATA',
  'ob.weight':      'WEIGHT (kg)',
  'ob.height':      'HEIGHT (cm)',
  'ob.age':         'AGE',
  'ob.sex':         'SEX',
  'ob.sex.m':       'Male',
  'ob.sex.f':       'Female',
  'ob.sex.o':       'Other',
  'ob.goal.title':  '🎯 WHAT IS YOUR GOAL?',
  'ob.goal.lose':   'LOSE WEIGHT',
  'ob.goal.lose.d': 'Caloric deficit and cardio',
  'ob.goal.define': 'GET LEAN',
  'ob.goal.define.d':'Tone muscles and reduce fat',
  'ob.goal.maintain':'MAINTAIN',
  'ob.goal.maintain.d':'Keep current body composition',
  'ob.goal.mass':   'BULK UP',
  'ob.goal.mass.d': 'Caloric surplus + high protein',
  'ob.goal.strength':'GAIN STRENGTH',
  'ob.goal.strength.d':'Maximum strength and power',
  'ob.activity.title':'🏃 ACTIVITY LEVEL',
  'ob.act.sedentary': 'SEDENTARY',
  'ob.act.sedentary.d':'Little or no exercise',
  'ob.act.light':   'LIGHTLY ACTIVE',
  'ob.act.light.d': 'Exercise 1-3 days/week',
  'ob.act.moderate':'MODERATELY ACTIVE',
  'ob.act.moderate.d':'Exercise 3-5 days/week',
  'ob.act.high':    'VERY ACTIVE',
  'ob.act.high.d':  'Intense training 6-7 days',
  'ob.act.athlete': 'ATHLETE',
  'ob.act.athlete.d':'Professional sport or physical job',
  'ob.class.title': '🧙 CHOOSE YOUR CLASS',
  'ob.class.warrior.d':'Master of close combat',
  'ob.class.mage.d': 'Devastating magic with protein bonus',
  'ob.class.archer.d':'Agile and swift, boosted by activity',
  'ob.class.healer.d':'Supreme resilience, fast HP recovery',
  'ob.summary':     '✅ SUMMARY!',
  'ob.btn.back':    '← BACK',
  'ob.btn.next':    'NEXT →',
  'ob.btn.play':    '⚔️ BEGIN ADVENTURE!',
  'ob.err.names':   'Enter your name and hero name!',
  'ob.err.data':    'Fill in all physical data!',
  'ob.err.goal':    'Choose your goal!',
  'ob.err.activity':'Choose your activity level!',
  'ob.err.class':   'Choose your character class!',

  /* HUD */
  'hud.lv':      'LV',
  'hud.streak':  'STREAK:',
  'hud.cal':     'cal',
  'hud.ml':      'ml',
  'hud.alert.hunger': 'HUNGRY!',
  'hud.alert.thirst': 'THIRSTY!',
  'hud.alert.weak':   'WEAKENED!',

  /* Tabs */
  'tab.home':    '🏠 HOME',
  'tab.log':     '📸 LOG',
  'tab.friends': '👥 FRIENDS',
  'tab.shop':    '🛒 SHOP',
  'tab.free':    '⚡ FREE BATTLE',

  /* Home */
  'home.castle':    '🏠 MY CASTLE',
  'home.stats':     '⚔️ HERO STATISTICS',
  'home.goals':     '🎯 TODAY\'S GOALS',
  'home.history':   '🏆 BATTLE HISTORY',
  'home.no_battles':'No battles yet.',
  'home.speech.hungry': 'I\'m so hungry! 🍗',
  'home.speech.thirsty':'I need water! 💧',
  'home.speech.weak':   'I feel weakened...',
  'home.speech.strong': 'I am very powerful! ⚡',
  'home.speech.ok':     'Take good care of me!',

  /* Stats */
  'stat.attack':  '⚔️ ATTACK',
  'stat.defense': '🛡️ DEFENSE',
  'stat.agility': '⚡ AGILITY',
  'stat.strength':'💪 STRENGTH',
  'stat.hp':      '❤️ HP',
  'stat.power':   '⚡ POWER',
  'stat.cal':     '🍽️ Calories',
  'stat.protein': '🥩 Protein',
  'stat.water':   '💧 Water',

  /* Log */
  'log.title':    '📸 LOG FOOD OR DRINK',
  'log.photo':    'TAP TO TAKE PHOTO',
  'log.type':     'TYPE',
  'log.desc':     'DESCRIPTION',
  'log.desc.ph':  'What did you eat?',
  'log.cal':      'CALORIES',
  'log.prot':     'PROTEIN(g)',
  'log.carbs':    'CARBS(g)',
  'log.water':    'WATER(ml)',
  'log.btn':      '⚔️ LOG AND GAIN EXPERIENCE',
  'log.today':    '📋 TODAY\'S LOG',
  'log.empty':    'No logs today. Start eating!',
  'log.type.food':'🍽️ Food',
  'log.type.water':'💧 Water',
  'log.type.drink':'🥤 Drink',
  'log.type.snack':'🍎 Snack',
  'log.type.supp': '💊 Supplement',
  'log.err.desc': 'Describe what you ate or drank!',

  /* Friends */
  'friends.my_id':    '🆔 YOUR ONLINE ID',
  'friends.copy_id':  '📋 COPY ID',
  'friends.add':      '➕ ADD FRIEND',
  'friends.add.name': 'Friend\'s username...',
  'friends.add.btn':  'ADD FRIEND',
  'friends.my_stats': '📊 MY BATTLE STATS',
  'friends.list':     '👥 FRIENDS',
  'friends.empty':    'No friends yet.\nShare your ID to play!',
  'friends.battle':   '⚔️ BATTLE',
  'friends.wins':     'wins',
  'friends.losses':   'losses',
  'friends.streak':   'day streak',
  'friends.coins':    'coins',
  'friends.added':    'added as friend!',
  'friends.err.name': 'Enter the friend\'s name!',
  'friends.logout':   'LOG OUT',

  /* Shop */
  'shop.title':   '🛒 THE KINGDOM SHOP',
  'shop.owned':   '✅ OWNED',
  'shop.none':    'Nothing yet',
  'shop.cat.all': 'ALL',
  'shop.cat.acc': '💍 ACCESSORIES',
  'shop.cat.arm': '⚔️ WEAPONS',
  'shop.cat.armor':'🛡️ ARMOR',
  'shop.cat.furn':'🪑 FURNITURE',
  'shop.cat.deco':'🖼️ DECORATIONS',
  'shop.bought':  'purchased!',
  'shop.no_coins':'Not enough coins!',

  /* Free Battle */
  'free.title':    '⚡ FREE BATTLE',
  'free.desc':     'Fight with no coin stakes!\nJust glory and fun.',
  'free.online':   '🌐 ONLINE CHALLENGE',
  'free.peer_ph':  'Paste your rival\'s ID...',
  'free.challenge':'⚡ CHALLENGE ONLINE',
  'free.cpu':      '🤖 PRACTICE OPPONENTS (CPU)',
  'free.fight':    '⚔️ FIGHT',
  'free.online.c': 'Connected online ✓',
  'free.online.cn':'Connecting...',
  'free.online.dc':'Not connected',
  'free.sent':     'Challenge sent! Waiting for response...',
  'free.err.id':   'Enter your rival\'s ID!',
  'free.incoming': '{name} challenges you to battle! {type}',
  'free.libre_type':'(FREE BATTLE)',
  'free.coins_type':'(WITH COINS)',
  'free.accept':   '✅ ACCEPT',
  'free.reject':   '❌ REJECT',
  'free.rejected': 'Rival rejected your challenge.',
  'free.accepted': 'Rival accepted! Starting battle...',
  'free.not_found':'Rival not found. Check the ID.',
  'free.err_conn': 'Online connection error.',

  /* Battle */
  'battle.start':  '{name} wants to battle!',
  'battle.begin':  'The battle begins!',
  'battle.attack': '⚔️ ATTACK',
  'battle.special':'✨ SPECIAL',
  'battle.defend': '🛡️ DEFEND',
  'battle.flee':   '🏃 FLEE',
  'battle.escaped':'{name} flees the battle... 😨',
  'battle.no_flee':'You can\'t escape! 😱',
  'battle.p_dmg':  '{name} uses {move}! -{dmg} HP to enemy.',
  'battle.p_crit': '{name} uses {move}! CRITICAL HIT! -{dmg} HP ⚡',
  'battle.e_dmg':  '{enemy} uses {move}! -{dmg} HP to {name}.',
  'battle.e_crit': '{enemy} uses {move}! CRITICAL! -{dmg} HP ⚡',
  'battle.victory':'{name} WON THE BATTLE! 🏆',
  'battle.defeat': '{name} was defeated... 💀',
  'battle.draw':   'The battle ended in a draw! 🤝',
  'battle.result.v':'VICTORY!',
  'battle.result.d':'DEFEAT',
  'battle.result.e':'DRAW',
  'battle.libre_note':'⚡ FREE BATTLE - No stakes',
  'battle.coins_won': '+{n} 🪙 coins stolen',
  'battle.coins_lost':'-{n} 🪙 coins lost',
  'battle.exp_gain':  '+{n} EXP',
  'battle.vs':        'vs',

  /* Level up */
  'lvlup.title': 'LEVEL UP!',
  'lvlup.nivel': 'LEVEL',
  'lvlup.gains': '⚔️ ATK +2 | 🛡️ DEF +2\n⚡ AGI +1 | 💪 STR +2\n❤️ HP MAX +15 | 🪙 +30',

  /* Battle history */
  'bh.victory': '🏆 VICTORY',
  'bh.defeat':  '💀 DEFEAT',
  'bh.draw':    '🤝 DRAW',

  /* Misc */
  'modal.close': 'CLOSE',
  'copied':      'ID copied to clipboard!',
  'daily_bonus': '🎉 {n}/3 goals met! +{coins} 🪙 | Streak: {streak} days',
  'ps_label':    'HP',

  /* Summary */
  'sum.player':  '👤 Player:',
  'sum.hero':    'Hero:',
  'sum.weight':  'Weight:',
  'sum.height':  'Height:',
  'sum.age':     'Age:',
  'sum.goal':    '🎯 Goal:',
  'sum.activity':'🏃 Activity:',
  'sum.cal_meta':'🔥 Calorie goal:',
  'sum.prot_meta':'🥩 Protein goal:',
  'sum.water_meta':'💧 Water goal:',
  'sum.stats':   '⚔️ Starting stats:',
  'sum.kg':      'kg',
  'sum.cm':      'cm',
  'sum.kcal_day':'kcal/day',
  'sum.g_day':   'g/day',
  'sum.ml_day':  'ml/day',
},

}; // end TRANSLATIONS

// ─── t() — translate with optional interpolation ─────────────────────────────────

window.t = function(key, vars) {
  const str = (TRANSLATIONS[window.LANG_CODE] || TRANSLATIONS.es)[key] || key;
  if (!vars) return str;
  return str.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? vars[k] : '{' + k + '}'));
};

window.setLang = function(code) {
  window.LANG_CODE = code;
  localStorage.setItem('hv_lang', code);
};
